-name: build and deploy to netlify
 
on:
 push: # trigger the code whwnever we push the code to the repo
  branches:
   -main
pull-request: # trigger the code whenever we merge the pr code from other branches 
  branches:
   -main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   -name: checkout code # checkout the code from github to the runner
    uses: actions/checkout@v4
    with:
    fetch-depth: 0
  -name: cache node modules # cache node modules to speed up the installation process
   uses: actions/cache@v3 # use cache version3 from github
   with:
    key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
    restore-keys: |
    ${{runner.os}}-node-
  -name: set up nodejs environment
   uses: actions/setup-node@v3
   with:
   node-version: '22'

  -name: install dependencies
   run: npm ci # install all dependencies via npm cli for faster installation
  
  -name: excute tests or run tests
   run: npm test # run tests to cache any error before deployment

  -name: build dependencies
   run: npm run build # build  
  
  -name: deploy to netlfiy
   uses: nwtgck/actions-netlify@v3.0.0
   with:
   publish-dir: './dist'
   production-branch: main
   github-token: ${{secrets.GITHUB_TOKEN}}
   deploy-message: deploy from github actions
   enable-pull-request-comment: false
   enable-comment-comment: true
   env:
    NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
    NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
   




