name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Step to check out the code from the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history for context

      - name: Cache Node modules  # Cache dependencies to speed up the process
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js  # Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the specific Node.js version 22

      - name: Install dependencies  # Install project dependencies using npm
        run: npm ci  # Clean install for reliable dependencies
      # temporarily disabled test steps
      #- name: Run tests  # Execute tests to ensure code quality
       # run: npm test  # Runs the test suite defined in package.json

      - name: Build  # Build the project
        run: npm run build  # Executes the build script defined in package.json

      - name: Deploy to Netlify  # Deploy the built project to Netlify
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './dist'  # Directory to publish
          production-branch: main  # Branch for production deployment
          github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          deploy-message: "Deploy from GitHub Actions"  # Custom deploy message
          enable-pull-request-comment: false
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Netlify authentication token
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Netlify site ID
